# Generated by Django 5.0.2 on 2024-02-10 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tag name', max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, help_text='SKU', max_length=100, null=True)),
                ('name', models.CharField(blank=True, help_text='Name of SKU', max_length=100, null=True)),
                ('category', models.CharField(blank=True, help_text='Category of SKU', max_length=100, null=True)),
                ('in_stocks', models.IntegerField(blank=True, default=0, help_text='Number of total stocks', null=True)),
                ('available_stocks', models.IntegerField(blank=True, default=0, help_text='Available stocks', null=True)),
                ('tags', models.ManyToManyField(blank=True, help_text='Tags associated with the item', to='items.tag')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
    ]
